steps:
# Install
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']

# Test
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'test:unit']

# Build
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'build']

# Deploy
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', '[SERVICE_NAME]', '--image', 'gcr.io/[PROJECT_ID]/[IMAGE]', '--region', '[REGION]', '--platform', 'managed', '--allow-unauthenticated']

#- name: 'gcr.io/$PROJECT_ID/firebase'
#  args: ['deploy']
